import Foundation
import TeebeCore
import Testing

/// The Swift port of the thinking-orbs geometry must reproduce the package's
/// own engine output (golden frames in `ThinkingOrbFixtures`, generated by
/// `scripts/thinking-orb-fixtures.mjs`).
@Suite("Thinking orb geometry")
struct ThinkingOrbTests {
    struct GoldenFrame: Decodable {
        let t: Double
        let dots: [[Double]]
    }

    struct GoldenState: Decodable {
        let mode: String
        let speed: Double
        let frames: [GoldenFrame]
    }

    struct Golden: Decodable {
        let size: Double
        let dotSize: Double
        let states: [String: GoldenState]
    }

    static let golden: Golden = {
        // swiftlint:disable:next force_try
        try! JSONDecoder().decode(Golden.self, from: Data(ThinkingOrbFixtures.json.utf8))
    }()

    static let tolerance = 1e-6

    func golden(_ state: ThinkingOrbState) throws -> GoldenState {
        let key = state == .solving ? "solving" : "breathing"
        return try #require(Self.golden.states[key])
    }

    @Test("the app's options match what the fixtures were generated with")
    func fixtureOptions() {
        #expect(Self.golden.size == ThinkingOrbStyle.size)
        #expect(Self.golden.dotSize == ThinkingOrbStyle.appDotSize)
    }

    @Test("preset speed matches the package", arguments: [ThinkingOrbState.solving, .breathing])
    func speed(state: ThinkingOrbState) throws {
        let style = ThinkingOrbStyle(state: state)
        #expect(abs(style.speed - (try golden(state)).speed) < Self.tolerance)
    }

    @Test("frames match the JS engine dot for dot", arguments: [ThinkingOrbState.solving, .breathing])
    func framesMatch(state: ThinkingOrbState) throws {
        let style = ThinkingOrbStyle(state: state)
        for frame in try golden(state).frames {
            let dots = style.frame(at: frame.t)
            try #require(dots.count == frame.dots.count, "dot count at t=\(frame.t)")
            for (dot, want) in zip(dots, frame.dots) {
                let got = [dot.x, dot.y, dot.z, dot.radius, dot.white, dot.alpha]
                for (lhs, rhs) in zip(got, want) {
                    #expect(abs(lhs - rhs) < Self.tolerance, "t=\(frame.t) got \(got) want \(want)")
                }
            }
        }
    }

    @Test("light substrates ramp the tint toward white, dark ones toward black")
    func inkRamp() {
        let tint = ThinkingOrbRGB(red: 20, green: 99, blue: 214)   // #1463d6
        #expect(tint.shaded(white: 0, dark: false) == tint)
        #expect(tint.shaded(white: 1, dark: false) == ThinkingOrbRGB(red: 255, green: 255, blue: 255))
        #expect(tint.shaded(white: 0.5, dark: false) == ThinkingOrbRGB(red: 138, green: 177, blue: 235))
        #expect(tint.shaded(white: 0, dark: true) == tint)
        #expect(tint.shaded(white: 1, dark: true) == ThinkingOrbRGB(red: 0, green: 0, blue: 0))
        #expect(tint.shaded(white: 0.5, dark: true) == ThinkingOrbRGB(red: 10, green: 50, blue: 107))
        // Ink values outside 0...1 are clamped, as the JS painter does.
        #expect(tint.shaded(white: -0.2, dark: false) == tint)
        #expect(tint.shaded(white: 1.4, dark: true) == ThinkingOrbRGB(red: 0, green: 0, blue: 0))
    }

    @Test("reduced motion shows the package's static representative frame")
    func staticFrame() {
        #expect(ThinkingOrbStyle.staticTime == 0.6)
    }
}
